name: NPM Publish Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    paths-ignore:
      - '**/CHANGELOG.md'
      - '**/package.json'

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.PAT_TOKEN }}
        persist-credentials: true

    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: 20
        registry-url: https://registry.npmjs.org

    - name: Set Git identity
      run: |
        git config user.name "kaushal-stc186"
        git config user.email "kaushal.kumar@seventhtriangle.com"

    - name: Bump Version (Conventional Commits)
      if: github.ref == 'refs/heads/main'
      run: |
        npm install -g standard-version
        standard-version --release-as patch --message "chore(release): %s [skip ci]"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Push version bump commit + tags
      if: github.ref == 'refs/heads/main'
      run: git push --follow-tags origin main

    - name: Publish to npm
      if: github.ref == 'refs/heads/main'
      run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}